/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SubscribeRouteImport } from './routes/subscribe'
import { Route as RoadmapRouteImport } from './routes/roadmap'
import { Route as IndexRouteImport } from './routes/index'
import { Route as PaymentCallbackRouteImport } from './routes/payment.callback'
import { Route as LessonModuleIdRouteImport } from './routes/lesson.$moduleId'

const SubscribeRoute = SubscribeRouteImport.update({
  id: '/subscribe',
  path: '/subscribe',
  getParentRoute: () => rootRouteImport,
} as any)
const RoadmapRoute = RoadmapRouteImport.update({
  id: '/roadmap',
  path: '/roadmap',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const PaymentCallbackRoute = PaymentCallbackRouteImport.update({
  id: '/payment/callback',
  path: '/payment/callback',
  getParentRoute: () => rootRouteImport,
} as any)
const LessonModuleIdRoute = LessonModuleIdRouteImport.update({
  id: '/lesson/$moduleId',
  path: '/lesson/$moduleId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/roadmap': typeof RoadmapRoute
  '/subscribe': typeof SubscribeRoute
  '/lesson/$moduleId': typeof LessonModuleIdRoute
  '/payment/callback': typeof PaymentCallbackRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/roadmap': typeof RoadmapRoute
  '/subscribe': typeof SubscribeRoute
  '/lesson/$moduleId': typeof LessonModuleIdRoute
  '/payment/callback': typeof PaymentCallbackRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/roadmap': typeof RoadmapRoute
  '/subscribe': typeof SubscribeRoute
  '/lesson/$moduleId': typeof LessonModuleIdRoute
  '/payment/callback': typeof PaymentCallbackRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/roadmap'
    | '/subscribe'
    | '/lesson/$moduleId'
    | '/payment/callback'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/roadmap'
    | '/subscribe'
    | '/lesson/$moduleId'
    | '/payment/callback'
  id:
    | '__root__'
    | '/'
    | '/roadmap'
    | '/subscribe'
    | '/lesson/$moduleId'
    | '/payment/callback'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  RoadmapRoute: typeof RoadmapRoute
  SubscribeRoute: typeof SubscribeRoute
  LessonModuleIdRoute: typeof LessonModuleIdRoute
  PaymentCallbackRoute: typeof PaymentCallbackRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/subscribe': {
      id: '/subscribe'
      path: '/subscribe'
      fullPath: '/subscribe'
      preLoaderRoute: typeof SubscribeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/roadmap': {
      id: '/roadmap'
      path: '/roadmap'
      fullPath: '/roadmap'
      preLoaderRoute: typeof RoadmapRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/payment/callback': {
      id: '/payment/callback'
      path: '/payment/callback'
      fullPath: '/payment/callback'
      preLoaderRoute: typeof PaymentCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lesson/$moduleId': {
      id: '/lesson/$moduleId'
      path: '/lesson/$moduleId'
      fullPath: '/lesson/$moduleId'
      preLoaderRoute: typeof LessonModuleIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  RoadmapRoute: RoadmapRoute,
  SubscribeRoute: SubscribeRoute,
  LessonModuleIdRoute: LessonModuleIdRoute,
  PaymentCallbackRoute: PaymentCallbackRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
