import type { Lesson } from "./types";

export const quadratic: Lesson = {
  slug: "quadratic",
  title: "Quadratic Equations",
  blurb: "Standard form, discriminant, the quadratic formula, and a live parabola.",
  steps: [
    { kind: "text", content: "Quadratic Equations", x: 80, y: 90, size: "h1" },
    { kind: "pause", ms: 250 },
    {
      kind: "text",
      content: "A quadratic is any equation you can write in the form:",
      x: 80,
      y: 170,
      size: "body",
    },
    { kind: "equation", content: "ax^2 + bx + c = 0", x: 120, y: 230 },
    { kind: "pause", ms: 300 },
    {
      kind: "text",
      content: "a, b, c are numbers   ·   a ≠ 0",
      x: 120,
      y: 300,
      size: "body",
    },
    {
      kind: "text",
      content: "The discriminant tells us how many real solutions there are:",
      x: 80,
      y: 370,
      size: "body",
    },
    { kind: "equation", content: "Δ = b^2 − 4ac", x: 120, y: 430 },
    {
      kind: "text",
      content: "Δ > 0 → two roots     Δ = 0 → one root     Δ < 0 → none",
      x: 120,
      y: 490,
      size: "body",
    },
    { kind: "pause", ms: 400 },
    {
      kind: "text",
      content: "And the quadratic formula gives us those roots:",
      x: 80,
      y: 560,
      size: "body",
    },
    {
      kind: "equation",
      content: "x = ( −b ± √(b^2 − 4ac) ) / 2a",
      x: 120,
      y: 620,
    },
    { kind: "pause", ms: 400 },
    {
      kind: "text",
      content: "Worked example:",
      x: 80,
      y: 710,
      size: "h2",
    },
    { kind: "equation", content: "x^2 − 5x + 6 = 0", x: 120, y: 770 },
    {
      kind: "text",
      content: "Factor:   (x − 2)(x − 3) = 0",
      x: 120,
      y: 830,
      size: "body",
    },
    {
      kind: "text",
      content: "So   x = 2   or   x = 3",
      x: 120,
      y: 880,
      size: "body",
    },
    { kind: "pause", ms: 400 },
    {
      kind: "text",
      content: "Now try it — drag the sliders and watch the curve:",
      x: 780,
      y: 170,
      size: "body",
    },
    { kind: "diagram", widget: "parabola", x: 780, y: 220, w: 620, h: 620 },
  ],
};